export const SET_LOADING = 'SET_LOADING';

export const SET_SNACKBAR_VISIBLE = 'SET_SNACKBAR_VISIBLE';
export const SET_SNACKBAR_TEXT = 'SET_SNACKBAR_TEXT';

export const SET_INITIAL_LOADING = 'SET_INITIAL_LOADING';
export const RESET_STATE = 'RESET_STATE';
export const SET_TOKEN = 'SET_TOKEN';
export const SET_USER = 'SET_USER';
